const Utils = {
  formatTime(minutes) {
    const h = Math.floor(minutes / 60);
    const m = minutes % 60;
    return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}`;
  },

  normalizeDate(date) {
    const d = new Date(date);
    d.setHours(0, 0, 0, 0);
    return d;
  },

  formatICSDate(date) {
    const pad = n => n < 10 ? '0' + n : n;
    return date.getFullYear() +
           pad(date.getMonth() + 1) +
           pad(date.getDate()) + 'T' +
           pad(date.getHours()) +
           pad(date.getMinutes()) + '00';
  },

  downloadICS(events) {
    if (!events || events.length === 0) {
      alert("Please generate a timetable first!");
      return;
    }

    let icsContent = "BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//StudyPlanAI//EN\n";

    events.forEach(event => {
      const startStr = this.formatICSDate(event.start);
      const endStr = this.formatICSDate(event.end);

      icsContent += "BEGIN:VEVENT\n";
      icsContent += `SUMMARY:Study ${event.subject}\n`;
      icsContent += `DTSTART:${startStr}\n`;
      icsContent += `DTEND:${endStr}\n`;
      icsContent += "DESCRIPTION:Generated by StudyPlan AI\n";
      icsContent += "END:VEVENT\n";
    });

    icsContent += "END:VCALENDAR";

    const blob = new Blob([icsContent], { type: "text/calendar" });
    const url = URL.createObjectURL(blob);
    
    const link = document.createElement("a");
    link.href = url;
    link.download = "my-study-plan.ics";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }
};